import Head from "next/head";
import Link from "next/link";
import { FaChartLine, FaCoins, FaList } from "react-icons/fa";
import { useState } from "react";
import { Header } from "~/components/Header";
import { Stake } from "~/components/Stake";
import PreconfTransactions from "~/components/PreconfTransactions";
import MainnetTransactions from "~/components/MainnetTransactions";
import HoodiTransactions from "~/components/HoodiTransactions";
import MainnetValidator from "~/components/MainnetValidator";


export default function Home() {
  const [activeTab, setActiveTab] = useState("stake");

  const renderContent = () => {
    switch (activeTab) {
      case "stake":
        return <Stake />;
      case "mainnet-validator":
        return <MainnetValidator />;
      case "preconf":
        return <PreconfTransactions />;
      case "hoodi":
        return <HoodiTransactions />;
      case "mainnet":
        return <MainnetTransactions />;
      default:
        return <Stake />;
    }
  };

  return (
    <>
      <Head>
        <title>Interstate Validators | Portal</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-row">
        <div className="flex min-h-screen w-72 tablet:w-60 flex-col pt-4 gap-8 border-r border-neutral-300">
          <div className="flex items-center gap-2 pl-4">
            <img src="/logo.png" className="h-auto w-8" />
            <h2 className="text-xl font-bold">Interstate</h2>
          </div>

          {/* TABS */}
          <div className="flex flex-col w-full items-start text-sm">
            <button
              onClick={() => setActiveTab("stake")}
              className={`w-full pl-4 py-3 flex items-center gap-2 hover:bg-neutral-100 duration-150 ease-in-out font-bold ${
                activeTab === "stake"
                  ? "bg-emerald-200 text-emerald-950"
                  : "bg-transparent text-black"
              }`}
            >
              <FaCoins />
             Hoodi Validator
            </button>

            <button
              onClick={() => setActiveTab("preconf")}
              className={`w-full pl-4 py-3 flex items-center gap-2 hover:bg-neutral-100 duration-150 ease-in-out font-bold ${
                activeTab === "preconf"
                  ? "bg-emerald-200 text-emerald-950"
                  : "bg-transparent text-black"
              }`}
            >
              <FaList />
              Hoodi Preconf Txns
            </button>
            
            <button
              onClick={() => setActiveTab("mainnet-validator")}
              className={`w-full pl-4 py-3 flex items-center gap-2 hover:bg-neutral-100 duration-150 ease-in-out font-bold ${
                activeTab === "mainnet-validator"
                  ? "bg-emerald-200 text-emerald-950"
                  : "bg-transparent text-black"
              }`}
            >
              <FaCoins />
              Mainnet Validator
            </button>


  
        
            <button
              onClick={() => setActiveTab("mainnet")}
              className={`w-full pl-4 py-3 flex items-center gap-2 hover:bg-neutral-100 duration-150 ease-in-out font-bold ${
                activeTab === "mainnet"
                  ? "bg-emerald-200 text-emerald-950"
                  : "bg-transparent text-black"
              }`}
            >
              <FaList />
              Mainnet Preconf Txns
            </button>
          </div>
        </div>

        <div className="flex flex-col w-full">
          {/* HEADER */}
          <Header />
          <div className="w-3/4 mt-14 items-center justify-center flex flex-row ml-auto mr-auto">
            {renderContent()}
          </div>

          {/* BOTTOM MARGIN */}
          <div className="mb-8"></div>
        </div>
      </main>
    </>
  );
}
